### ISSUE TITLE
About CLIP decoding

### ISSUE THREAD

**Issue by hrodruck** [hmillerbakewell/clip-gaze#1]
Hey, I saw your comment on [this reddit thread](https://www.reddit.com/r/MachineLearning/comments/yix10u/d_is_there_a_way_to_decode_clip_features_to_a/) about CLIP text decoding and I'd like to inform you of a repository that does that.

This repository: https://github.com/dhg-wei/DeCap looks like just an image captioning repository, on the surface. But, in the backbone, their method first projects the image embedding to text space and THEN decodes it. Their paper is super clear about that. 

They have a pretrained model available, though some light tweaking may be necessary to remove the input image requirement.

Cheers

**Comment by hmillerbakewell** [comment]
Thank you for bringing that to my attention!
